### ISSUE TITLE
JaegerAutoConfiguration and @ConditionalOnClass(io.jaegertracing.Tracer.class)

### ISSUE THREAD

**Issue by timtebeek** [opentracing-contrib/java-spring-jaeger#12]
Hi! In trying to adopt `opentracing-spring-jaeger-starter` I was quite surprised to find [`JaegerAutoConfiguration`](https://github.com/opentracing-contrib/java-spring-jaeger/blob/master/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerAutoConfiguration.java) has a `@ConditionalOnClass(io.jaegertracing.Tracer.class)` annotation, which fails to match with newer versions of Jaeger. This silently falls back to a No-OpTracer; a warning would have been nice. :)

It appears the `io.jaegertracing.Tracer` class was removed from Jaeger-Core in version 0.30.0. Are there any plans to support newer versions of Jaeger? Or should I stick to older versions for now?

**Comment by geoand** [comment]
Hello and thanks for reporting this!

I haven't been able to update the project with the latest and greatest Jaeger stuff because I was caught up in other work.
I should be able to start working on this soon

**Comment by geoand** [comment]
#13 should fix the issue. You are more than welcome to try it @timtebeek.

I am waiting for a review on it first before merging it since I am not an expert on the Jaeger Java client :)

**Comment by timtebeek** [comment]
hey awesome, thanks for the quick work! That seems to work indeed; Still exploring, but should at least be better than not registering a tracer anymore. :) Looking forward to the next release!

**Comment by geoand** [comment]
I will cut a `0.2.0` soon. I am planning to bump the minor version since there are some changes in the interface signatures that will break users of the old versions.

**Comment by geoand** [comment]
`0.2.0` has been released and should be available in Maven Central in a few hours
