### ISSUE TITLE
Jaeger not propagating TraceId to other microservice

### ISSUE THREAD

**Issue by LiewShanWei** [opentracing-contrib/java-spring-jaeger#136]
I have a repository that imports `opentracing-spring-jaeger-web-starter 3.3.1`.
So i cloned 2 copies and changed `server.port` for each of them.

I then did a rest api call to the first copy, inside which will automatically make a rest api call to the second copy.
First api log: `Span reported: 1c423b9003fab8fd:1c423b9003fab8fd:0:1`
Second api log: `Span reported: 7edfe66cf60ba855:7edfe66cf60ba855:0:1`

In both my console and jaeger UI, the traceId is not propagated to the second api call.
Am i missing anything?

**Comment by AhHa45** [comment]
Can you describe your setup a little bit more?
Sounds like you have only one service that is instrumentalized?

**Comment by LiewShanWei** [comment]
I found the root cause. Turns out i was initializing a new `RestTemplate` object in my `RestController` methods using `RestTemplate restTemplate = new RestTemplate();` by accident.

I will close this issue, thanks for helping!
