### ISSUE TITLE
Global JAEGER_TAGS environment variable is not used by spring starter. 

### ISSUE THREAD

**Issue by mwenk-cc** [opentracing-contrib/java-spring-jaeger#16]
The auto config class (io.opentracing.contrib.java.spring.jaeger.starter.JaegerAutoConfiguration) creates a tracer in such a way that it does not add tags.   It also would not use any of the other JAEGER_* env variables that the Jaeger client looks for.  

This showed to us by not adding the JAEGER_TAGS to our traces.

**Comment by mwenk-cc** [comment]
PR for this: https://github.com/opentracing-contrib/java-spring-jaeger/pull/17

**Comment by mwenk-cc** [comment]
Close PR as intended solution had issues.  

The spring starter should use environment variables if environment variables are there.  So this issue is still open from that perspective.

**Comment by geoand** [comment]
I will look into `JAEGER_TAGS` but I don't agree that the env vars should be used if they are there.
If the user wanted that, they could just go ahead and use declare a bean from `Configuration.fromEnv().getTracerBuilder()`.
Having said that I will look into ways to provide even more configuration

**Comment by pavolloffay** [comment]
Why not to provide tags as map via spring config?

**Comment by geoand** [comment]
@pavolloffay Thanks for the suggestion, I plan to look into this soon

**Comment by sagaranand015** [comment]
@geoand: Any update on this please?
We have a use case to inject the JAEGER_TAGS values from environment, so looking around for this support. 
Thanks a ton!

**Comment by geoand** [comment]
@sagaranand015 I just created #36 to address this

**Comment by sagaranand015** [comment]
This is lovely! 
Eagerly waiting for it be to be merged and released. Thank you @geoand

**Comment by geoand** [comment]
You're welcome!

Once I get a review, I'll merge and do a release

**Comment by ledor473** [comment]
> Why not to provide tags as map via spring config?
I don't see a way to provide a map of Tags via `application.yml`/Spring Config

**Comment by geoand** [comment]
> > Why not to provide tags as map via spring config?
> 
> I don't see a way to provide a map of Tags via `application.yml`/Spring Config.
> 
> I think supporting both `JAEGER_TAGS` + a map from application.yml might be good!

That's pretty much what the PR does :wink:

**Comment by ledor473** [comment]
Oh I missed that part. That's indeed what it does :)

**Comment by geoand** [comment]
Version `1.0.2` is on the way with a fix on this
