### ISSUE TITLE
Should we rename it to java-spring-tracer-configuration?

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-spring-jaeger#2]
java-spring-web auto-configure contains an auto-configuration which resolves a  tracer bean
https://github.com/opentracing-contrib/java-spring-web/blob/master/opentracing-spring-web-autoconfigure/src/main/java/io/opentracing/contrib/spring/web/autoconfig/TracerAutoConfiguration.java#L33. 

All auto-configuration in java-spring-web and java-spring-cloud depends on this class. I think it would be better to move it here and keep this project related to tracer bean resolution.

Then jaeger config can depend on the module with TracerAutoConfiguration and fully import it - see https://github.com/opentracing-contrib/java-spring-jaeger/pull/1/files#diff-5cb4f2e88e04516e692b889149318617R54

**Comment by geoand** [comment]
So if I understand correctly @pavolloffay, you propose to move the `java-spring-web-auto-configure` module into the repo and rename this repo to have a more appropriate name?

**Comment by pavolloffay** [comment]
No, I propose to move this class https://github.com/opentracing-contrib/java-spring-web/blob/master/opentracing-spring-web-autoconfigure/src/main/java/io/opentracing/contrib/spring/web/autoconfig/TracerAutoConfiguration.java#L33 to this repo into a separate artifact

**Comment by pavolloffay** [comment]
Then web and cloud projects would depend on this thin artifact.

**Comment by geoand** [comment]
That makes perfect sense to me, :+1: from me

**Comment by pavolloffay** [comment]
Based on discussion with @objectiser we will keep a starter module per tracer. This way vendors can create starters with different instrumentations - we will also split java-spring-cloud to instrumentation per module.

I will create a separate project for TracerAutoConfiguration.

**Comment by geoand** [comment]
Cool
