### ISSUE TITLE
Config option to disable Jaeger globally?

### ISSUE THREAD

**Issue by wittwerch** [opentracing-contrib/java-spring-jaeger#20]
We are integrating Jaeger into our Spring Boot microservices. However in some cases, like running locally or in test we don't want Jaeger to be enabled.
Is there a config option to disable Jaeger? As a workaround I found the following solution, which allows us to enable/disable it by a custom env variable.

```java
    @Bean
    public io.opentracing.Tracer jaegerTracer() {

        if (Boolean.valueOf(System.getenv("JAEGER_ENABLED"))) {
            return Configuration.fromEnv().getTracer();
        }
        else {
            Reporter reporter = new InMemoryReporter();
            Sampler sampler = new ConstSampler(false);
            return new JaegerTracer.Builder("untraced-service")
                    .withReporter(reporter)
                    .withSampler(sampler)
                    .build();
        }

    }
```

**Comment by geoand** [comment]
Hi @wittwerch.

There most certainly is such a property, you can find it [here](https://github.com/opentracing-contrib/java-spring-jaeger/blob/572ccd92cc71cd335a1bfc56e1a2b326754fbb30/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerConfigurationProperties.java#L31) and it controls the Spring Boot auto-configuration mechanism as can be seen [here](https://github.com/opentracing-contrib/java-spring-jaeger/blob/572ccd92cc71cd335a1bfc56e1a2b326754fbb30/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerAutoConfiguration.java#L53).

**Comment by geoand** [comment]
If the suggestion above fits what you need, feel free to close the issue

**Comment by geoand** [comment]
Closing this. If you feel that it has not been resolved, feel free to reopen

**Comment by wittwerch** [comment]
Hi @geoand 

Thansk for checking back, however I was on holiday so sorry for the late response.

I tried to switch my setting to configuring opentracing entirely throw properties, so I can use the proposed switch to turn it on and off. But somehow that doesn't work.

First I removed the `jaegerTracer` method.
Second I updated my Spring profile
```
spring:
  application:
    name: MyApp

opentracing:
  jaeger:
    enabled: true
    const-sampler:
      decision: true
    http-sender:
      url: http://jaeger-collector:14268/api/traces
```

But then booting the app fails:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of method reporter in io.opentracing.contrib.java.spring.jaeger.starter.JaegerAutoConfiguration required a bean of type 'io.opentracing.contrib.java.spring.jaeger.starter.ReporterAppender' that could not be found.


Action:

Consider defining a bean of type 'io.opentracing.contrib.java.spring.jaeger.starter.ReporterAppender' in your configuration.
```

I have honestly no clue what I should do. Yes define a bean, but then do what?

Additonally when I _disable_ the tracer in the config, during boot I get the following error:
```
Error resolving tracer using io.jaegertracing.tracerresolver.internal.JaegerTracerResolver@7e8aeeab: Service name must not be null or empty
```
According to the doc that should not happen: `unknown-spring-boot Will be used as the service-name if no value has been specified to the property spring.application.name`.
I mean I have set the `spring.application.name` and even the fallback to `unknown-spring-boot` is not working.

I'm not sure whether these issues are connected, so maybe you could point me in the right direction? 

Thanks!

**Comment by geoand** [comment]
@wittwerch I am thinking about this again, but I would like to here more about your use case.

IIUC, what you need to is to run your tests and have everything setup but not have the traces / spans be reported?

**Comment by wittwerch** [comment]
Actually we are running Jaeger on our OpenShift environment. There we have all kind of different namespaces (test, dev, prod, review) and only in a few of them we want the tracing to be active. We spin up such namespaces for all kind of purposes (reviewing new features for example).

In that case it would be very handy to have the tracing enabled/disabled over environment variables (or properties) without touching the code (same Docker image).

**Comment by geoand** [comment]
@wittwerch The issue that you are seeing when you set `opentracing.jaeger.enabled` to `false` is explained like so:

When you include this starter, `io.opentracing.contrib:opentracing-spring-tracer-configuration-starter` is also included since it performs some necessary plumbing.
However, when `opentracing.jaeger.enabled` is set to `false`, then that dependency provides a default `Tracer` implementation that needs the `JAEGER_SERVICE_NAME` environment variable (see [this](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/README.md)).

One simple way around this would be to do the following:

```java
@ConditionalOnProperty(value = "opentracing.jaeger.enabled", havingValue = "false", matchIfMissing = false)
public class MyTracerConfiguration {

    @Bean
    public io.opentracing.Tracer jaegerTracer() {
         final Reporter reporter = new InMemoryReporter();
         final Sampler sampler = new ConstSampler(false);
         return new JaegerTracer.Builder("untraced-service")
                    .withReporter(reporter)
                    .withSampler(sampler)
                    .build();
        }
    }

}
```

Here we are reusing the `opentracing.jaeger.enabled` property to define a Tracer that doesn't do anything.
Mind giving it a shot?

I am wondering if something like the above should go into the README. WDYT @wittwerch ?

**Comment by wittwerch** [comment]
Yes, that works perfectly in case I want to disable the tracer!

Unfortunately the enabled tracer still doesn't work, when configured by the starter. It is still complaining about the reporter bean missing.

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reporter' defined in class path resource [io/opentracing/contrib/java/spring/jaeger/starter/JaegerAutoConfiguration.class]: Unsatisfied dependency expressed through method 'reporter' parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.opentracing.contrib.java.spring.jaeger.starter.ReporterAppender' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=false)}
```

I noticed that I can get around this by configuring it from environment variables. 

```
return io.jaegertracing.Configuration.fromEnv().getTracer();
```
 
But then I can't use the property-based configuration provided by the "java-spring-jaeger" package.

Any thoughts about that?

**Comment by geoand** [comment]
Glad to hear that disabling works :)

I am still not clear however what exactly your doing during the enable scenario that is not working.
Would you mind explaining it again please? I can't seem to determine which part of issue is about the disable part and which is about enable :)

**Comment by geoand** [comment]
@wittwerch IIUC, simply using:

```
spring:
  application:
    name: MyApp

opentracing:
  jaeger:
    enabled: true
    const-sampler:
      decision: true
    http-sender:
      url: http://jaeger-collector:14268/api/traces
```

causes the application to fail?

**Comment by geoand** [comment]
Awesome, great to hear you fixed it!

No wonder I wasn't seem the issue :)

**Comment by wittwerch** [comment]
Yes true :) Thanks for your support, appreciate it!

**Comment by geoand** [comment]
You're welcome!

**Comment by tinnapat** [comment]
> @wittwerch The issue that you are seeing when you set `opentracing.jaeger.enabled` to `false` is explained like so:
> 
> When you include this starter, `io.opentracing.contrib:opentracing-spring-tracer-configuration-starter` is also included since it performs some necessary plumbing.
> However, when `opentracing.jaeger.enabled` is set to `false`, then that dependency provides a default `Tracer` implementation that needs the `JAEGER_SERVICE_NAME` environment variable (see [this](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/README.md)).
> 
> One simple way around this would be to do the following:
> 
> ```java
> @ConditionalOnProperty(value = "opentracing.jaeger.enabled", havingValue = "false", matchIfMissing = false)
> @Configuration
> public class MyTracerConfiguration {
> 
>     @Bean
>     public io.opentracing.Tracer jaegerTracer() {
>          final Reporter reporter = new InMemoryReporter();
>          final Sampler sampler = new ConstSampler(false);
>          return new JaegerTracer.Builder("untraced-service")
>                     .withReporter(reporter)
>                     .withSampler(sampler)
>                     .build();
>         }
>     }
> 
> }
> ```
> 
> Here we are reusing the `opentracing.jaeger.enabled` property to define a Tracer that doesn't do anything.
> Mind giving it a shot?
> 
> I am wondering if something like the above should go into the README. WDYT @wittwerch ?

Sorry for replying on such an old thread. Is it possible to add above code, which configure NoopTracer when `opentracing.jaeger.enabled` is `false` in to next version of this library instead of library user has to manually add it in to their application?

Thank you very much.
