### ISSUE TITLE
JaegerTracerCustomizer is deprecated

### ISSUE THREAD

**Issue by lainekendall** [opentracing-contrib/java-spring-jaeger#23]
`JaegerTracerCustomizer` is [mentioned in the README](https://github.com/opentracing-contrib/java-spring-jaeger#iojaegertracingtracerbuilder-customization) but is only a part of the previous and now deprecated version of this repository (https://github.com/snowdrop/opentracing-tracer/blob/master/opentracing-tracer-autoconfigure/src/main/java/me/snowdrop/opentracing/tracer/JaegerTracerCustomizer.java). 
Maybe it should be removed from the README and be replaced by something else.

**Comment by geoand** [comment]
Thanks for pointing this out!

I'll check it in tomorrow
