### ISSUE TITLE
Question about NoopMetricProvider

### ISSUE THREAD

**Issue by tvfoodmaps** [opentracing-contrib/java-spring-jaeger#31]
Hi, pretty new to Jaeger so this may be a poor question.

The doc says "NoopMetricsFactory is used - effectively meaning that no metrics will be collected", yet when I go to http://localhost:16686/metrics I still see a lot of metrics collected so I'm trying to understand what is going on?

**Comment by geoand** [comment]
Hi!

The metrics that this starter configures, are purely client side metrics, meaning that they capture that state/operations that were performed on the client side (the traced application).
What you are seeing in `http://localhost:16686/metrics` are the metrics of the Jaeger itself.

Does that make sense?

**Comment by geoand** [comment]
The easiest thing to do would be to define:

```
 @Bean
  public MetricsFactory metricsFactory() {
    return new InMemoryMetricsFactory();
  }
```

Then you could query that in your code to see what sort of capturing operations Jaeger Client Java has been up to

**Comment by tvfoodmaps** [comment]
Thanks, that code seems to work but once I get back that object later in the code there doesn't seem to be an easy way to traverse and see all the metrics?  All of the get operations assume I know the name of what was created - which I don't :-)

Ultimately I'm trying to see what metrics I can expose to be consumed / polled by prometheus like the http://localhost:16686/metrics address.

**Comment by geoand** [comment]
In that case, I would suggest you take a look at the micrometer metrics integration that the jaeger java client provides. See: https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-micrometer

You would need to add a dependency, set the correct bean and then hopefully your metrics endpoint will contain the tracing data as well.

**Comment by tvfoodmaps** [comment]
I clearly don't fully get how to do this :-)

So my current config already has micrometer working with spring so that /actuators/prometheus has the standard Spring metrics.

My gradle has:

```
    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile('io.opentracing.contrib:opentracing-spring-jaeger-cloud-starter:1.0.1')
    compile('io.jaegertracing:jaeger-micrometer:0.32.0')
    compile('io.micrometer:micrometer-registry-prometheus:latest.release')

```

When I add:
`compile('io.opentracing.contrib:opentracing-metrics-prometheus-spring-autoconfigure:0.3.0')
`
The same /actuators/prometheus URI now has Jaeger span info (yeah!) but I lost the standard metrics from Spring.  Can I have both or am I being greedy?

**Comment by tvfoodmaps** [comment]
I finally got this working using the java metrics project, although it took a lot of trial and error.  

Ultimately I included:

```
compile('io.opentracing.contrib:opentracing-metrics-micrometer:0.3.0')
compile('io.opentracing.contrib:opentracing-metrics-spring-autoconfigure:0.3.0')

```

And then a file (not exactly sure what this is doing):

```
package ketocentral.config;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Bean;
import io.opentracing.contrib.metrics.MetricsReporter;
import io.opentracing.contrib.metrics.micrometer.MicrometerMetricsReporter;
import io.opentracing.tag.Tags;
import io.opentracing.Scope;
import io.opentracing.Span;
import io.opentracing.Tracer;

@Configuration
public class TraceMetrics{

  @Bean
  public MetricsReporter myReporter(){
    MicrometerMetricsReporter.Builder builder = MicrometerMetricsReporter.newMetricsReporter();
    builder.withName("jaeger_spans");
    return builder.build();
  }
}
```

Hopefully this helps someone else.

**Comment by geoand** [comment]
Thanks @tvfoodmaps!
