### ISSUE TITLE
Documentation: Wrong configuration property name for RateLimitingSampler

### ISSUE THREAD

**Issue by gyuuu** [opentracing-contrib/java-spring-jaeger#33]
In Readme.md on master branch as well as on 0.2.2 tag
This is the actual example:
opentracing.jaeger.rate-limiting-max-traces-per-second = value

This one works for version 0.2.2
opentracing.jaeger.rate-limiting-sampler.max-traces-per-second = value

**Comment by geoand** [comment]
Thanks for spotting it @gyuuu !

Fixed in #11c9a6d
