### ISSUE TITLE
Reactor support

### ISSUE THREAD

**Issue by msoub** [opentracing-contrib/java-spring-jaeger#34]
First of all, many thanks for the lib!

It looks like [Reactor](https://projectreactor.io/) is not supported by the library. Another [lib](https://github.com/opentracing-contrib/java-reactor) supports it based on what has been done in Spring Cloud Sleuth.

Is there a will to support it directly in java-spring-jaeger?

**Comment by geoand** [comment]
Hey @msoub 

There is an [issue](https://github.com/opentracing-contrib/java-spring-cloud/issues/150) to support WebFlux but currently it hasn't received much attention.
If such support lands, then it would be picked up here as well

**Comment by msoub** [comment]
WebFlux support would be nice but as a first step I guess it would be simpler to add the support of Reactor for inner fluxes.

**Comment by geoand** [comment]
True.

@pavolloffay I think that OpenTracing does RxJava right? Is there anything relevant for Project Reactor?

**Comment by geoand** [comment]
Support was recently in https://github.com/opentracing-contrib/java-spring-web so we should probably bump soon to get such support

**Comment by geoand** [comment]
Closing since reactor support has already been added
