### ISSUE TITLE
Allow to configure serviceName

### ISSUE THREAD

**Issue by holledauer** [opentracing-contrib/java-spring-jaeger#38]
The serviceName of the tracer is set to ${spring.application.name} in JaegerAutoConfiguration. It would be great if you would allow that the serviceName can be set to a different value.

Background: Our spring application name is the same on all our environments and all environments send the traces to a single jaeger instance. As all the instances of the app on all environments have the same tracer serviceName it is not possible to configure the sampling rate for each environment. Therefore we need to set the tracer serviceName to something like ${spring.application.name}-${env}

**Comment by geoand** [comment]
@holledauer Please take a look at #39 and let me know what you think about it

**Comment by holledauer** [comment]
Yes, this is exactly what i need. Many thanks!

**Comment by geoand** [comment]
Cool, I will merge it then and cut a `1.0.3` release.
