### ISSUE TITLE
No service dependencies shown in jaeger 

### ISSUE THREAD

**Issue by derXear** [opentracing-contrib/java-spring-jaeger#42]
Hello, 

i have a minimal example with 2 Spring Boot Apps where one calls the other. 
I can see all spans of the apps in the Jaeger UI, but no dependency between the apps. Shouldn't this already work by autoconfiguration?

Here is a [link](https://github.com/derXear/opentracing-spring-boot-jaeger-example) to the minimal example. If it's not a bug, maybe someone could push me into the right direction at Stackoverflow [here](https://stackoverflow.com/questions/55239593/service-dependencies-not-shown-in-jaeger-between-spring-boot-applications) :)

Thanks in advance

**Comment by pavolloffay** [comment]
Hi @derXear if you can see spans in UI it means that there is nothing wrong with the instrumentation (this project).

Dependencies require an additional process to generate them https://www.jaegertracing.io/docs/1.10/deployment/#aggregation-jobs-for-service-dependencies

**Comment by derXear** [comment]
Hi @pavolloffay 
but shouldn't spark not be necessary when all-in-one jaeger is used as stated in the first paragraph of the project [jaeger-spark-dependencies](https://github.com/jaegertracing/spark-dependencies#jaeger-spark-dependencies)? 
![jaeger-spark-dependencies](https://user-images.githubusercontent.com/19554842/54631193-c5b64380-4a7b-11e9-8d9d-ba6475c15ddb.png)
