### ISSUE TITLE
missing spans with spring boot 2.1.5 and flux WebClient

### ISSUE THREAD

**Issue by pstitt** [opentracing-contrib/java-spring-jaeger#50]
spring-jaeger-cloud-starter 2.0.0
spring-boot 2.1.5

I have an issue with missing spans that only happens after upgrading from spring boot 2.1.4 to 2.1.5

The application has a rest controller that in turn uses the webflux WebClient to call back to itself (just to demonstrate the issue).

The expected trace is:

    - hello
        - GET /world
            - world
                - sleep

With 2.1.5 the outcome is:

    - hello
        - Get /world
    - sleep

Because the world controller span is missing, its child spans lose their context.

Attached is a project that demonstrates it working with spring boot 2.1.4 and the spans being logged to console.

Run with gradle bootRun and hit localhost:8080/hello

Update the spring boot version to 2.1.5 and repeat to see the "world" span is missing.

[spring-cloud-tracing-bug.tar.gz](https://github.com/opentracing-contrib/java-spring-jaeger/files/3268701/spring-cloud-tracing-bug.tar.gz)

**Comment by geoand** [comment]
@ask4gilles any ideas?

**Comment by ask4gilles** [comment]
@geoand I'm able to reproduce the issue but I've no clue about the cause :/

**Comment by geoand** [comment]
Thanks for checking! 

I'm have very few cycles currentlly so I won't be able to look at it very sooon.

**Comment by geoand** [comment]
@ask4gilles do you plan on checking if the new `2.1.1` version of java-spring-web fixes this?

**Comment by ask4gilles** [comment]
@geoand I did yes and that's what I was hoping for ...but it does not solve it. At least, now we have the same baseline to write a new IT for example...

**Comment by ask4gilles** [comment]
@geoand @pstitt 

- Using SB2.1.5 and Adding `spring-boot-starter-tomcat` instead of netty and it works.
- Using SB2.1.5 and Netty and downgrading reactor to `io.projectreactor.netty:reactor-netty:0.8.6.RELEASE` and it works too.
So my guess is a change on the projectreactor netty stack. I don't know if it's bug or if is the intended behaviour, but you should investigate on this direction.

**Comment by geoand** [comment]
Thanks for the info @ask4gilles !

**Comment by geoand** [comment]
@ask4gilles thanks for linking the ticket!

**Comment by geoand** [comment]
Is this still an issue if one uses `2.1.6.RELEASE` version of Spring Boot?

**Comment by ask4gilles** [comment]
@geodand I don’t see why it would

**Comment by geoand** [comment]
You're probably right since the issue is still open, just wondering :)

**Comment by pstitt** [comment]
Yes, I tried 2.1.6 and it’s still an issue.

**Comment by ask4gilles** [comment]
As mentioned, I don’t think it’s an issue (certainly not in SB) but rather a change in reactor-netty, see my last comment.

**Comment by pstitt** [comment]
It's magically fixed in springboot 2.1.7.RELEASE which uses reactor-netty 0.8.10.RELEASE

**Comment by geoand** [comment]
The best kind of issue 😂
