### ISSUE TITLE
Add custom headers

### ISSUE THREAD

**Issue by Hohenheimsenberg** [opentracing-contrib/java-spring-jaeger#55]
I'm working with Istio/Envoy + Jaeger,  
Envoy uses an extra header **x-request-id**
https://istio.io/docs/tasks/telemetry/distributed-tracing/overview/

Is it possible to add it?
Maybe with a `TracerBuilderCustomizer`

**Comment by pavolloffay** [comment]
yes, you will need to enable B3 propagation:
https://github.com/opentracing-contrib/java-spring-jaeger/blob/master/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerConfigurationProperties.java#L57
