### ISSUE TITLE
JAEGER_SERVICE_NAME from jaeger-operator not respected

### ISSUE THREAD

**Issue by camelpunch** [opentracing-contrib/java-spring-jaeger#56]
The [jaeger-operator](https://github.com/jaegertracing/jaeger-operator) for Kubernetes modifies app/service containers to have a `JAEGER_SERVICE_NAME` environment variable. However, java-spring-jaeger wants e.g. `OPENTRACING_JAEGER_SERVICE_NAME`.

With many microservices, mapping these env vars using beans is a little cumbersome. I'm not sure which project should make it possible to configure the env var name. Do you think it would make sense to respect `JAEGER_SERVICE_NAME` as well as `OPENTRACING_JAEGER_SERVICE_NAME`?

**Comment by geoand** [comment]
We could certainly do it easily here. 
@pavolloffay would something like this make sense?

**Comment by camelpunch** [comment]
Here's the place where it's hardcoded in the operator: https://github.com/jaegertracing/jaeger-operator/blob/9cdd514655654a92de5a70b58fda2797d6a6a32b/pkg/inject/sidecar.go#L30

**Comment by objectiser** [comment]
Yes it would be good if the env vars from the operator (`JAEGER_SERVICE_NAME` and `JAEGER_PROPAGATION`) were respected.

**Comment by geoand** [comment]
@camelpunch would you like to provide a PR? If that's not possible, I will get to it some time soon

**Comment by camelpunch** [comment]
Yeah I'll take a look.

**Comment by geoand** [comment]
Awesome, thanks!

**Comment by geoand** [comment]
Closed by #57
