### ISSUE TITLE
Can't work in spring cloud gateway

### ISSUE THREAD

**Issue by hiColors** [opentracing-contrib/java-spring-jaeger#62]
gateway -> consumer -> provider，but can't work in spring cloud gateway。

spring cloud gatway pom

- version

```propreties
    <spring-cloud.version>Greenwich.SR2</spring-cloud.version>
    <spring-boot.version>2.1.7.RELEASE</spring-boot.version>
```

- pom

```xml
<dependency>
    <groupId>io.opentracing.contrib</groupId>
    <artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
    <version>2.0.3</version>
</dependency>

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-gateway</artifactId>
</dependency>
```

- demo code

https://github.com/life-labs/jaeger-example-spring-cloud/tree/master/sc-without-sleuth

**Comment by pavolloffay** [comment]
What do you mean by can't work? you don't see traces or the app crashes?

**Comment by hiColors** [comment]
- this is use spring cloud gateway

![image](https://user-images.githubusercontent.com/17754408/64105276-7dc87600-cda8-11e9-83fe-6ecebefaa992.png)

- this is use spring cloud netflix zuul

![image](https://user-images.githubusercontent.com/17754408/64105399-bc5e3080-cda8-11e9-8cba-8378737f2022.png)

in spring cloud gateway , Span is not linked 。

**Comment by nicorbes** [comment]
Hi guys, I run into the same issue. And we still couldn't find any proper solution.

We created a GlobalFilter to generate the span and pass the traceID to the next service. And it is working... but the problem is that we are creating the local spring cloud gateway span with the incoming request instead of the outgoing... that's why this solution is not so good.

Does some of you know how to interact with the underneath HttpClientConnect object?

I left the code explanation and also de question on [stackoverglow](https://stackoverflow.com/questions/57694618/does-someone-implement-jaeger-with-spring-cloud-gateway).

If there is other approach to address this, please let us know, maybe we can help...

Thanks in advance!

**Comment by caorui31** [comment]
@nicorbes 
I have the same question
All I can do is pass the trace information when I receive the request, but there is no way to associate it with the request at the time of receiving the response. 
Is there any temporary solution on your side?

**Comment by nicorbes** [comment]
@caorui31 partially yes, we created as mentioned before, the following filter:

```java
@ConditionalOnProperty(value = "opentracing.jaeger.enabled", havingValue = "true")
@Configuration
public class TraceIDSenderConfiguration {

    private Logger log = LoggerFactory.getLogger(TraceIDSenderConfiguration.class);

    public TraceIDSenderConfiguration() {
        log.info("Initiating tracing configuration...");
    }

    @Bean
    @Order(-1)
    public GlobalFilter tracingFilter() {
        return (exchange, chain) -> {
            ServerHttpRequest request = exchange.getRequest();
            ServerHttpRequest.Builder requestBuilder = request.mutate();

            Span span = null;

            try {
                Tracer tracer = TracerResolver.resolveTracer();

                // TODO: This is not right, we should create the span based on the downstream request
                span = tracer.buildSpan("FORWARD")
                        .withTag(Tags.SPAN_KIND.getKey(), Tags.SPAN_KIND_CLIENT)
                        .withTag(Tags.HTTP_METHOD.getKey(), request.getMethod().name())
                        .withTag(Tags.HTTP_URL.getKey(), request.getPath().toString())
                        .asChildOf(tracer.activeSpan())
                        .start();

                tracer.inject(span.context(), Format.Builtin.HTTP_HEADERS, new RequestBuilderCarrier(requestBuilder));
            } catch (Exception e) {
                log.warn("Tracing not initiated", e);
            }

            Span finalSpan = span;
            return chain.filter(exchange.mutate()
                    .request(requestBuilder.build())
                    .build()).then(Mono.fromRunnable(() -> {
                ServerHttpResponse response = exchange.getResponse();

                if (finalSpan != null) {
                    finalSpan.setTag(Tags.HTTP_STATUS, response.getStatusCode().value());
                    finalSpan.finish();
                }
            }));
        };
    }

    public static class RequestBuilderCarrier implements TextMap {

        private final ServerHttpRequest.Builder requestBuilder;

        RequestBuilderCarrier(ServerHttpRequest.Builder requestBuilder) {
            this.requestBuilder = requestBuilder;
        }

        @Override
        public Iterator<Map.Entry<String, String>> iterator() {
            throw new UnsupportedOperationException("carrier is write-only");
        }

        @Override
        public void put(String key, String value) {
            requestBuilder.header(key, value);
        }
    }
}
```

It works, since you receive the traceID on the next chained service, but it you look in the information provided for the parent span it doesn't work... since it grab information for the incoming request and not the downstream one... we are still looking for the proper solution...

**Comment by hiColors** [comment]
I have already solved this bug, I am testing it, and I will release the code later.
in spring cloud gateway, @see org.springframework.cloud.gateway.filter.headers.HttpHeadersFilter,

**Comment by hiColors** [comment]
this is pr link!

https://github.com/opentracing-contrib/java-spring-cloud/pull/247

**Comment by HaojunRen** [comment]
I met this issue too, now any update？

**Comment by HaojunRen** [comment]
i saw this pr has been mergered，But when the new version will release？thanks

**Comment by geoand** [comment]
I had kicked off `0.3.10`  yesterday but it seems to have failed. I am restarting it

**Comment by geoand** [comment]
`0.3.10` should sync to central by tomorrow if all goes well

**Comment by israeljesus2zup** [comment]
Is this feature already available? I'm facing the same problem
