### ISSUE TITLE
Disable reporting spans for actuator endpoints

### ISSUE THREAD

**Issue by mariusgiger** [opentracing-contrib/java-spring-jaeger#63]
Hi guys,

When using Jaeger for Spring Cloud Gateway with actuator endpoints enabled (e.g. /actuator/health for K8s readiness probe), all calls to the actuator endpoints produce a span. Is there a way to disable this behaviour?

Config:
```
        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-spring-cloud-starter</artifactId>
            <version>0.3.2</version>
        </dependency>
```

Cheers,
Marius

**Comment by geoand** [comment]
Hi,

I vaguely remember something of this sort, but can't put my finger on it.
@pavollofay or @ask4gilles do you remember?

If not, I can look through the code obviously 😆
