### ISSUE TITLE
How can I configure the properties by Configuration?

### ISSUE THREAD

**Issue by LeBW** [opentracing-contrib/java-spring-jaeger#67]
I want to configure the properties by Configuration in Java code instead of by external Properties. Is there any way to do that? Thank you.

**Comment by geoand** [comment]
Sure, you can override any of the beans specified here: https://github.com/opentracing-contrib/java-spring-jaeger/blob/master/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerAutoConfiguration.java

**Comment by LeBW** [comment]
> Sure, you can override any of the beans specified here: https://github.com/opentracing-contrib/java-spring-jaeger/blob/master/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerAutoConfiguration.java

So whether I can infer that, If I want to change the host, I need to:
1. Overwrite the Reporter bean.
2. add a line: `properties.setHost("host")`.
3. Remain the others.

But I still have two questions.
1. Is it a recommended way to do like that? I think that all of the configurations is in the object `JaegerConfigurationProperties`. Is there a way to modify this object directly instead of overwrite another bean?

2. If I modify the properties in a bean(such as in reporter), what about else beans? Will the properties be modified automatically in other beans(like in sampler)?

Thank you very much.

**Comment by geoand** [comment]
The suggested way to us is to use the properties defined by `JaegerConfigurationProperties`.

Overriding the beans is a more "advanced" used-case which would only be used if you need to define something that can't be expressed with the properties.
Defining any of the beans doesn't prevent auto-configuration of the other beans. Only the ones you define will be "overriden", the rest will just be configured via the set properties.

**Comment by LeBW** [comment]
> The suggested way to us is to use the properties defined by `JaegerConfigurationProperties`.
> 
> Overriding the beans is a more "advanced" used-case which would only be used if you need to define something that can't be expressed with the properties.
> Defining any of the beans doesn't prevent auto-configuration of the other beans. Only the ones you define will be "overriden", the rest will just be configured via the set properties.

OK. Thank you very much

**Comment by geoand** [comment]
> > The suggested way to us is to use the properties defined by `JaegerConfigurationProperties`.
> > Overriding the beans is a more "advanced" used-case which would only be used if you need to define something that can't be expressed with the properties.
> > Defining any of the beans doesn't prevent auto-configuration of the other beans. Only the ones you define will be "overriden", the rest will just be configured via the set properties.
> 
> OK. Thank you very much

You are welcome :)
