### ISSUE TITLE
Upgrade to jaeger 1.1.0

### ISSUE THREAD

**Issue by Nick-Anderssohn** [opentracing-contrib/java-spring-jaeger#69]
I noticed issue #48 talks about upgrading to jaeger 0.35.1. I think that issue should have been closed actually since this now uses jaeger 0.35.1. Unfortunately, a couple other high severity CVEs have been discovered in the version of lib-thrift that is used by jaeger 0.35.1. Jaeger 1.1.0 uses a newer version of lib-thrift that doesn't have those CVEs, so hopefully we can upgrade. These are the CVEs I am referring to:
* https://ossindex.sonatype.org/vuln/42dec0ea-acb2-4560-8317-3360e79aa333
* https://ossindex.sonatype.org/vuln/326b0d95-8aa6-40d7-8901-0478505f8b54

**Comment by geoand** [comment]
Thanks for reporting!

Would you like to send a PR updating the version?

**Comment by Nick-Anderssohn** [comment]
@geoand Sorry for the delay, PR #77 bumps the version.

**Comment by svenstaro** [comment]
Well, can't this issue be closed?
