### ISSUE TITLE
use NoopTracer for disabling tracing 

### ISSUE THREAD

**Issue by gerloh** [opentracing-contrib/java-spring-jaeger#80]
The suggested implementation for disabeling in the readme uses a   `ConstSampler `and a   `InMemoryReporter` . This is still tracing but not sampling (sending) the traces. Why not  `NoopTracerImpl ` by opentracing instead ? 
Also the `InMemoryReporter` has a memory leak ? It is only gathering spans in an arraylist, never releases them ...
https://github.com/opentracing-contrib/java-spring-jaeger#completely-disable-tracing

**Comment by geoand** [comment]
Hi,

Would you like to send a PR with your suggestion?

**Comment by pavolloffay** [comment]
Isn't it better to just disable the Jager or opentracing-spring-cloud artifacts in spring configuration? 

IIRC if the jaeger is disabled the noop tracer might be used by default. I am not sure though.

**Comment by gerloh** [comment]
I mean this : 
https://github.com/opentracing-contrib/java-spring-jaeger/pull/82

**Comment by gerloh** [comment]
> Isn't it better to just disable the Jager or opentracing-spring-cloud artifacts in spring configuration?
> 
> IIRC if the jaeger is disabled the noop tracer might be used by default. I am not sure though.

Probably, but readme suggested that's not a solution ?

**Comment by geoand** [comment]
PR merged
