### ISSUE TITLE
Make W3C context propagation configurable

### ISSUE THREAD

**Issue by fischerman** [opentracing-contrib/java-spring-jaeger#89]
Similar to B3, it would be nice to have the recently added W3C context propagation in this library.
This would require an update of the Jaeger client library to v 1.2.0.

**Comment by chgl** [comment]
Interested in this as well. For now I was able to implement it by registering a TraceBuilderCustomizer:

```java
    @Bean
    public TracerBuilderCustomizer traceContextJaegerTracerCustomizer() {
        return builder -> {
            var injector = new TraceContextCodec.Builder().build();

            builder.registerInjector(Format.Builtin.HTTP_HEADERS, injector)
                    .registerExtractor(Format.Builtin.HTTP_HEADERS, injector);

            builder.registerInjector(Format.Builtin.TEXT_MAP, injector)
                    .registerExtractor(Format.Builtin.TEXT_MAP, injector);
        };
    }
```

copy-and-pasted from 
 https://github.com/opentracing-contrib/java-spring-jaeger/blob/f8f921b26b52555ec19da1cd2e0194b151c10d81/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerAutoConfiguration.java#L208

Library versions:

```groovy
    implementation "io.opentracing.contrib:opentracing-spring-web-starter:3.0.1"
    implementation "io.opentracing.contrib:opentracing-spring-jaeger-web-starter:3.1.2"
    implementation "io.opentracing.contrib:opentracing-spring-jaeger-cloud-starter:3.1.2"
    implementation "io.jaegertracing:jaeger-client:1.3.2"
```
