### ISSUE TITLE
enable128-bit-traces has no effect

### ISSUE THREAD

**Issue by JasonMing** [opentracing-contrib/java-spring-jaeger#90]
Setting `opentracing.jaeger.enable128-bit-traces` to `true` has no effects while I find following codes of `JaegerAutoConfiguration`
https://github.com/opentracing-contrib/java-spring-jaeger/blob/a44aedec17cd80947dd931edd4418407e7a88e6e/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerAutoConfiguration.java#L63-L79

It seems not set the flags of `enable128-bit-traces` and `enable-b3-propagation`.

Affected version: 3.1.1

**Comment by agaudreault-jive** [comment]
It seems to be done here
https://github.com/opentracing-contrib/java-spring-jaeger/blob/master/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerAutoConfiguration.java#L207-L234

**Comment by geoand** [comment]
Thats is correct

**Comment by agaudreault-jive** [comment]
hmmm it seems like the property name might missmatch
In the config code it's `@ConditionalOnProperty(value = "opentracing.jaeger.enable-128-bit-traces")` 

But in the config file, VS Code doesn't suggest me the same name
![image](https://user-images.githubusercontent.com/47184027/85324145-4e017080-b497-11ea-871d-d1d0a9d70558.png)

So maybe the mapping with the config file and the property name doesn't work ? I dont know how to validate that mapping in Spring.

**Comment by geoand** [comment]
Ah, good catch!

This probably changed with Spring Boot 2.x.

Would you like to submit a PR to fix `@ConditionalOnProperty`?

**Comment by agaudreault-jive** [comment]
Should we use `enable128-bit-traces` and change @ConditionalOnProperty and other references, or use `@Value("${opentracing.jaeger.enable-128-bit-traces}")` on the property ?

**Comment by geoand** [comment]
Let's just make the change to `@ConditionalOnProperty(value = "opentracing.jaeger.enable128-bit-traces")`.

IntelliJ is also suggesting that it's the right match

**Comment by agaudreault-jive** [comment]
Actually this doesn't seems to be the problem. The test are passing with `"opentracing.jaeger.enable128-bit-traces=true"` or `"opentracing.jaeger.enable-128-bit-traces=true"`. And according to SpringBoot 2.0, both should be supported https://spring.io/blog/2018/03/28/property-binding-in-spring-boot-2-0. I will test it in our current deployment see if it works or not.

**Comment by agaudreault-jive** [comment]
Well, it works fine, so I think we can close this. 

Configuration: `enable128-bit-traces: true`
128-bit Trace: `https://localhost:8080/trace/a4f06630032838b3a941b5d7350f2978`
Regular Trace: `https://localhost:8080/trace/c4a5944822e16513`

**Comment by geoand** [comment]
I tried this as well and it worked for me too.

I'll close this, but feel free to reopen if you have more information to provide @JasonMing
