### ISSUE TITLE
Document how to use remote sampling

### ISSUE THREAD

**Issue by svenstaro** [opentracing-contrib/java-spring-jaeger#95]
In the README you document every other sampler but not the remote sampling. I think it'd make sense to also document that.

**Comment by geoand** [comment]
Hi,

Would you like to contribute that to the documentation?

Thanks

**Comment by svenstaro** [comment]
Honestly, no because I'm stuck at this part and would like the documentation to exist so I can progress. :P

**Comment by geoand** [comment]
I'll try to do when I get some cycles

**Comment by svenstaro** [comment]
@geoand friendly ping. :)

**Comment by geoand** [comment]
See https://github.com/opentracing-contrib/java-spring-jaeger/pull/111
